const MODULE_NAME = 'ETH'

/* getters */
const GETTERS = {
    WEB3: 'WEB3',
    CONTRACT_INSTANCE: 'CONTRACT_INSTANCE'
}

const MODULE_GETTERS = {
    [GETTERS.WEB3]: `${MODULE_NAME}/${GETTERS.WEB3}`,
    [GETTERS.CONTRACT_INSTANCE]: `${MODULE_NAME}/${GETTERS.CONTRACT_INSTANCE}`
}

/* mutations */
const MUTATIONS = {
    REGISTER_WEB3_INSTANCE: 'REGISTER_WEB3_INSTANCE'
}

/* actions */
const ACTIONS = {
    REGISTER_WEB3: 'REGISTER_WEB3'
}

const MODULE_ACTIONS = {
    [ACTIONS.REGISTER_WEB3]: `${MODULE_NAME}/${ACTIONS.REGISTER_WEB3}`
}

export {MODULE_NAME, GETTERS, MODULE_GETTERS, MUTATIONS, ACTIONS, MODULE_ACTIONS}