const MODULE_NAME = 'TOPICS'

/* getters */
const GETTERS = {
    LOADING_TOPICS: 'LOADING_TOPICS',
    PAGINATION_TOPICS: 'PAGINATION_TOPICS',
    TOPICS: 'TOPICS'
}

const MODULE_GETTERS = {
    [GETTERS.LOADING_TOPICS]: `${MODULE_NAME}/${GETTERS.LOADING_TOPICS}`,
    [GETTERS.PAGINATION_TOPICS]: `${MODULE_NAME}/${GETTERS.PAGINATION_TOPICS}`,
    [GETTERS.TOPICS]: `${MODULE_NAME}/${GETTERS.TOPICS}`
}

/* mutations */
const MUTATIONS = {
    SET_PAGINATION_TOPICS: 'SET_PAGINATION_TOPICS',
    SET_TOPIC: 'SET_TOPIC',
    ADD_TOPIC: 'ADD_TOPIC'
}

/* actions */
const ACTIONS = {
    GET_TOPIC: 'GET_TOPIC',
    SAVE_TOPIC: 'SAVE_TOPIC'
}

const MODULE_ACTIONS = {
    [ACTIONS.GET_TOPIC]: `${MODULE_NAME}/${ACTIONS.GET_TOPIC}`,
    [ACTIONS.SAVE_TOPIC]: `${MODULE_NAME}/${ACTIONS.SAVE_TOPIC}`,
    [ACTIONS.SET_PAGINATION_TOPICS]: `${MODULE_NAME}/${ACTIONS.SET_PAGINATION_TOPICS}`
}

export {MODULE_NAME, GETTERS, MODULE_GETTERS, MUTATIONS, ACTIONS, MODULE_ACTIONS}