const MODULE_NAME = 'WORKS'

/* getters */
const GETTERS = {
    LOADING: 'LOADING',
    PAGINATION: 'PAGINATION',
    ITEMS: 'ITEMS'
}

const MODULE_GETTERS = {
    [GETTERS.LOADING]: `${MODULE_NAME}/${GETTERS.LOADING}`,
    [GETTERS.PAGINATION]: `${MODULE_NAME}/${GETTERS.PAGINATION}`,
    [GETTERS.ITEMS]: `${MODULE_NAME}/${GETTERS.ITEMS}`
}

/* mutations */
const MUTATIONS = {
    SET_PAGINATION: 'SET_PAGINATION',
    SET_ITEM: 'SET_ITEM',
    ADD_ITEM: 'ADD_ITEM'
}

/* actions */
const ACTIONS = {
    SET_PAGINATION: 'SET_PAGINATION',
    GET_ITEM: 'GET_ITEM',
    SAVE_ITEM: 'SAVE_ITEM'
}

const MODULE_ACTIONS = {
    [ACTIONS.SET_PAGINATION]: `${MODULE_NAME}/${ACTIONS.SET_PAGINATION}`,
    [ACTIONS.GET_ITEM]: `${MODULE_NAME}/${ACTIONS.GET_ITEM}`,
    [ACTIONS.SAVE_ITEM]: `${MODULE_NAME}/${ACTIONS.SAVE_ITEM}`
}

export {MODULE_NAME, GETTERS, MODULE_GETTERS, MUTATIONS, ACTIONS, MODULE_ACTIONS}